name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:debian

    steps:
      - uses: actions/checkout@v6
      - run: uv run ruff check
      - run: uv run ruff format --check
      - run: uv run --script main.py
